"use client";

import { useEffect, useMemo, useState } from "react";
import useSWR from "swr";
import { Archive, ArrowLeft, Copy, FileQuestion, Plus, Search, Users } from "lucide-react";
import { QuestionnaireBuilder, emptyQuestionnaire } from "@/components/questionnaire-builder";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect } from "@/components/ui/native-select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { Panel } from "@/components/panel";
import { StatStrip } from "@/components/stat-strip";
import {
  ApiError, archiveQuestionnaireTemplate, assignQuestionnaire, createQuestionnaireTemplate,
  duplicateQuestionnaireTemplate, listClients, listQuestionnaireTemplates, listQuestionnaireVersions,
  type Client, type QuestionnaireTemplate, type QuestionnaireVersion,
} from "@/lib/api";
import { clientsKey, questionnairesKey } from "@/lib/swr-keys";

export default function QuestionnairesPage() {
  const [includeArchived, setIncludeArchived] = useState(false);
  const { data, error, mutate } = useSWR(questionnairesKey(includeArchived), () => listQuestionnaireTemplates(includeArchived));
  const { data: clients } = useSWR(clientsKey(), listClients);
  const [search, setSearch] = useState(""); const [editing, setEditing] = useState<QuestionnaireTemplate | null>(null);
  const [versions, setVersions] = useState<QuestionnaireVersion[]>([]); const [createOpen, setCreateOpen] = useState(false);
  const [assigning, setAssigning] = useState<QuestionnaireTemplate | null>(null); const [confirmArchive, setConfirmArchive] = useState<QuestionnaireTemplate | null>(null);
  const templates = useMemo(() => (data ?? []).filter((t) => `${t.name} ${t.description ?? ""}`.toLowerCase().includes(search.toLowerCase())), [data, search]);
  const open = async (template: QuestionnaireTemplate) => { setEditing(template); setVersions(await listQuestionnaireVersions(template.id)); };
  if (editing) return <div className="mx-auto flex w-full max-w-[96rem] flex-col gap-6"><Button className="self-start" variant="ghost" onClick={() => setEditing(null)}><ArrowLeft /> Questionnaire library</Button><QuestionnaireBuilder template={editing} versions={versions} onSaved={(saved, version) => { setEditing(saved); if (version) setVersions((v) => [...v, version]); void mutate(); }} /></div>;
  return <div className="mx-auto flex w-full max-w-[96rem] flex-col gap-6">
    <header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div className="flex flex-col gap-2"><h1 className="text-4xl leading-tight font-thin tracking-tight [font-family:var(--font-denton)] md:text-5xl">Questionnaires</h1><p className="max-w-2xl text-sm text-pretty text-muted-foreground">Build reusable intake forms, publish stable versions, and assign them explicitly to clients.</p></div><Button onClick={() => setCreateOpen(true)}><Plus /> New questionnaire</Button></header>
    {error && <p className="text-sm text-destructive">{error instanceof ApiError ? error.message : String(error)}</p>}
    <StatStrip label="Questionnaire summary" loading={!data} items={[{ label: "Templates", value: data?.filter((t) => !t.archived_at).length ?? 0, detail: "Available to your firm" }, { label: "Archived", value: data?.filter((t) => t.archived_at).length ?? 0, detail: includeArchived ? "Shown below" : "Hidden from the library" }, { label: "Clients", value: clients?.length ?? 0, detail: "Available for explicit assignment" }]} columns="grid-cols-3" />
    <Panel title="Library" meta={data ? `${templates.length}` : undefined} action={<label className="flex items-center gap-2 text-xs text-muted-foreground"><Switch checked={includeArchived} onCheckedChange={setIncludeArchived} /> Show archived</label>}><div className="flex flex-col gap-4"><div className="relative"><Search className="absolute top-2.5 left-3 size-4 text-muted-foreground" /><Input className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search questionnaires" /></div>{!data ? <p className="text-sm text-muted-foreground">Loading questionnaires…</p> : templates.length === 0 ? <div className="py-5"><p className="font-medium">No questionnaires found</p><p className="text-sm text-muted-foreground">Create a questionnaire to begin building a reusable client intake.</p></div> : <ul className="divide-y divide-border/50">{templates.map((template) => <li key={template.id} className="grid gap-3 py-4 md:grid-cols-[minmax(0,1fr)_auto] md:items-center"><button className="min-w-0 text-left" onClick={() => void open(template)}><span className="flex items-center gap-2 text-sm font-medium"><FileQuestion className="size-4" /> {template.name}{template.archived_at && <span className="rounded-full bg-muted px-2 py-0.5 text-[10px] text-muted-foreground">Archived</span>}</span><span className="mt-1 block text-xs text-muted-foreground">{template.description || "No description"} · {template.latest_published_version ? `Published v${template.latest_published_version}` : "Draft only"} · Updated {new Date(template.updated_at).toLocaleDateString()}</span></button><div className="flex flex-wrap gap-1"><Button size="sm" variant="ghost" onClick={() => void open(template)} disabled={!!template.archived_at} title={template.archived_at ? "Archived questionnaires are read-only. Duplicate it to make changes." : undefined}>Edit draft</Button><Button size="sm" variant="ghost" onClick={() => setAssigning(template)} disabled={!!template.archived_at}><Users /> Assign</Button><Button size="sm" variant="ghost" onClick={async () => { await duplicateQuestionnaireTemplate(template.id); void mutate(); }}><Copy /> Duplicate</Button><Button size="sm" variant="ghost" onClick={() => setConfirmArchive(template)} disabled={!!template.archived_at}><Archive /> Archive</Button></div></li>)}</ul>}</div></Panel>
    <CreateDialog open={createOpen} onOpenChange={setCreateOpen} onCreated={(t) => { setCreateOpen(false); void mutate(); void open(t); }} />
    {assigning && <AssignDialog template={assigning} clients={clients ?? []} open onOpenChange={(open) => !open && setAssigning(null)} />}
    <Dialog open={!!confirmArchive} onOpenChange={(open) => !open && setConfirmArchive(null)}><DialogContent><DialogHeader><DialogTitle>Archive questionnaire?</DialogTitle><DialogDescription>Existing assignments, published versions, and submissions stay available. This template cannot be assigned again.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setConfirmArchive(null)}>Cancel</Button><Button variant="destructive" onClick={async () => { if (confirmArchive) await archiveQuestionnaireTemplate(confirmArchive.id); setConfirmArchive(null); void mutate(); }}>Archive</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function CreateDialog({ open, onOpenChange, onCreated }: { open: boolean; onOpenChange: (open: boolean) => void; onCreated: (t: QuestionnaireTemplate) => void }) {
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Create questionnaire</DialogTitle><DialogDescription>Start with one editable section and question. You can save the draft before publishing.</DialogDescription></DialogHeader><div className="flex flex-col gap-4"><label className="flex flex-col gap-1.5"><Label>Name</Label><Input autoFocus value={name} onChange={(e) => setName(e.target.value)} /></label><label className="flex flex-col gap-1.5"><Label>Description</Label><Textarea value={description} onChange={(e) => setDescription(e.target.value)} /></label>{error && <p className="text-sm text-destructive">{error}</p>}</div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={!name.trim() || busy} onClick={async () => { setBusy(true); setError(null); try { onCreated(await createQuestionnaireTemplate({ name: name.trim(), description: description || null, draft_definition: emptyQuestionnaire(), draft_document_rules: { format_version: "1", rules: [] } })); } catch (e) { setError(e instanceof ApiError ? e.message : String(e)); } finally { setBusy(false); } }}>{busy ? "Creating…" : "Create"}</Button></DialogFooter></DialogContent></Dialog>;
}

function AssignDialog({ template, clients, open, onOpenChange }: { template: QuestionnaireTemplate; clients: Client[]; open: boolean; onOpenChange: (open: boolean) => void }) {
  const [clientId, setClientId] = useState(clients[0]?.id ?? 0); const [versions, setVersions] = useState<QuestionnaireVersion[]>([]); const [versionId, setVersionId] = useState(0); const [required, setRequired] = useState(false); const [respondent, setRespondent] = useState("client"); const [period, setPeriod] = useState("unspecified"); const [label, setLabel] = useState(""); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { void listQuestionnaireVersions(template.id).then((items) => { setVersions(items); setVersionId(items.at(-1)?.id ?? 0); }); }, [template.id]);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Assign {template.name}</DialogTitle><DialogDescription>Assignments are pinned to the selected published version. No email is sent automatically.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><label className="flex flex-col gap-1"><Label>Client</Label><NativeSelect value={clientId} onChange={(e) => setClientId(Number(e.target.value))}>{clients.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</NativeSelect></label><label className="flex flex-col gap-1"><Label>Published version</Label><NativeSelect value={versionId} onChange={(e) => setVersionId(Number(e.target.value))}>{versions.map((v) => <option key={v.id} value={v.id}>Version {v.version_number}</option>)}</NativeSelect></label><label className="flex flex-col gap-1"><Label>Respondent</Label><Input value={respondent} onChange={(e) => setRespondent(e.target.value)} /></label><label className="flex flex-col gap-1"><Label>Reporting period key</Label><Input value={period} onChange={(e) => setPeriod(e.target.value)} /></label><label className="flex flex-col gap-1 sm:col-span-2"><Label>Reporting period label</Label><Input value={label} onChange={(e) => setLabel(e.target.value)} placeholder="For example, 2025 tax year" /></label><label className="flex items-center gap-2 text-sm sm:col-span-2"><Switch checked={required} onCheckedChange={setRequired} /> Required before document uploads</label>{message && <p className="text-sm sm:col-span-2">{message}</p>}</div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Close</Button><Button disabled={!clientId || !versionId} onClick={async () => { try { await assignQuestionnaire(clientId, { version_id: versionId, is_required: required, respondent_identifier: respondent, reporting_period_key: period, reporting_period_label: label || null }); setMessage("Assigned. Use the client profile to copy or send the existing portal link."); } catch (e) { setMessage(e instanceof ApiError ? e.message : String(e)); } }}>Assign questionnaire</Button></DialogFooter></DialogContent></Dialog>;
}
